{
  "language": "python",
  "python": "3.6.1",
  "install": [
    "pip install -r requirements.txt"
  ],
  "script": [
    "nosetests --with-coverage"
  ],
  "after_success": "coveralls",
  "cache": "pip",
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}


